name: mis_vehiculos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  mockito: ^5.4.2
  path: ^1.8.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0+2
  dropdown_button2: ^2.3.9
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
